### ISSUE TITLE
Consistent XML error when parsing.

### ISSUE THREAD

**Issue by christwainwright** [ownaginatious/fbchat-archive-parser#11]
Hey, I'm just trying to parse many conversations and see the stats (basic stuff first) but I keep getting thrown this error every time I try at the same point, no matter what command I issue:

"The streaming parser crashed due to malformed XML. Falling back to the less strict/efficient python html.parser. It may take a while before you see output..."

It then kills the process.

Thoughts?

**Comment by ownaginatious** [comment]
Hi, thanks for reporting this.

Could you give me more details? Example: operating system, python version, library version (newest is `0.7.post8`. etc)

**Comment by christwainwright** [comment]
Sure! It's Ubuntu 14.04.2 LTS, python 2.7.6 and the newest library version.

**Comment by ownaginatious** [comment]
Okay cool, I can reproduce that environment perfectly. Out of curiosity, how large is your `messages.htm` file? This sounds like it may be the OS unexpectedly reaping the process due to running out of memory.

I'm working on getting the primary streaming parser to stop being too sensitive to avoid this issue.

**Comment by christwainwright** [comment]
It's about 5 years worth of messages so it might very well be a size issue.

**Comment by christwainwright** [comment]
it's about 100mb.

**Comment by ownaginatious** [comment]
Yeah, I have another report of memory running out with an 80 MB `messages.htm` file. I'm going to try swapping for a different XML parser and see if that helps. I'll post back here when it's ready!

**Comment by ownaginatious** [comment]
Hi there, I think I've fixed the issue. Please try version `0.7.post10` and let me know if that fixes it.

**Comment by christwainwright** [comment]
Will do, thanks =)

**Comment by christwainwright** [comment]
It didn't throw back that error this time, it just kept going until it stopped and said 'Killed'. Not sure if that's a printout when it's actually done or it just killed itself during the process.

**Comment by ownaginatious** [comment]
Hmm, was there progress text still being displayed? (i.e. `Discovered chat thread with [...]`)

It could be that there is simply too much data. You could try using the `-t` switch (see the main page for examples) to just extract specific threads, rather than trying to do the whole thing in one go.

I may try doing something with temp files to get around the fact that most people's chat logs are huge somewhere down the line.

**Comment by christwainwright** [comment]
Yeah no progress text, it's probably the same issue. I've been playing with -t and it seems to do the trick anyway. Thanks!

**Comment by ownaginatious** [comment]
Do you never see progress text? It should be printing out either way :/

**Comment by christwainwright** [comment]
Oh, I see the progress text, I mean not once it's killed. There's text until then. It was sort of an unnecessary statement on my end - obviously once it's killed there's no text. Ha

**Comment by ownaginatious** [comment]
Ah okay, good to know. Looks like it's just a memory issue then. I'll try to think of a way to deal with that for the next release. Thanks!
