### ISSUE TITLE
Unexpected time format

### ISSUE THREAD

**Issue by jetXS** [ownaginatious/fbchat-archive-parser#15]
Hey,

My facebook language settings are in EN-US as you suggested.. The archive was exported under those settings... Still getting this error however.. what do you think ?

```
Unexpected time format in "Thursday, September 22, 2011 at 3:09pm EDT". This program only accepts English locale time formatting. 
If you downloaded your Facebook data in a different language, please temporarily switch your language settings to English (US), re-download, and try again. 
If that doesn't help, then please report this as a bug on the associated GitHub page. 
```

Thank you for your time !

**Comment by ownaginatious** [comment]
Hey, thanks for submitting this! I realized this approach probably doesn't work if your computer's locale is French (or anything other than English) due to the computer only understanding things like "lundi" instead of "Monday".

I'm working on a fix utilizing the library suggested in the other open issue and should have it out by the end of the day.

**Comment by jetXS** [comment]
Wow awesome !! thank you for your hard work !!! 👍

**Comment by ownaginatious** [comment]
Added in `0.8`. Build is currently broken because of a third-party dependency under certain old versions of Python, but I'm working on it.

Please let me know if that improves things for you.

**Comment by jetXS** [comment]
Seems to be fixed !! thank you !! :)
