### ISSUE TITLE
Polish locale

### ISSUE THREAD

**Issue by MeQuake** [ownaginatious/fbchat-archive-parser#41]
Hi, big thanks for you tool!
I have a problem with polish archive version:

> Unexpected time format in "18 listopada 2016 o 22:20 UTC+01". If you downloaded your Facebook data in a language other than English, then it's possible support may need to be added to this tool.

I was researching it, the problem is with month names. For example in english we have months called this way:
**January, February, March [...] November, December**
Facebook translate month names in archive in polish genitive:
**Stycznia, Lutego, Marca [...] Listopada, Grudnia**
while arrow.get contains only simple month names:
**Styczeń, Luty, Marzec [...] Listopad, Grudzień**

Here is [EXAMPLE](https://repl.it/H8Hp/2)

Using babel.dates could probably resolve this issue:

[Format date with month name in polish in python](http://stackoverflow.com/questions/3654423/format-date-with-month-name-in-polish-in-python/3654627#3654627)

[Babel dates documnatation](http://babel.pocoo.org/en/latest/api/dates.html)

I was trying to implement it but I couldn't resolve problem I had:
AttributeError: 'str' object has no attribute 'tzinfo'

Could you look into this issue? I will be grateful!
Sorry for not marking this with bug label, seems I can't do it or don't know how to use it.

**Comment by ownaginatious** [comment]
Hi there, thank you for looking into this! Another user was having the same issue with Czech, but it turned out to be avoidable since Facebook happened to use the same case endings.

Could you provide a stack trace or a sample of the code you changed to cause the error? It's hard to tell what the issue is without any context.

I'm tempted to say that the solution should be implemented in the `arrow` library, given that what they currently have sounds like it's basically useless for producing date strings for highly inflected languages, like Polish. Would it ever make sense to have `Listopad` in a date string vs `Listopada` in Polish? If not, maybe it makes sense to just fix the locale there. That, or extend each locale to have a "long month name" alternative.

**Comment by MeQuake** [comment]
Sure, here are my [changes](https://github.com/MeQuake/fbchat-archive-parser/commit/dfb33e931cbcd95d846b08a0c1cc67d3322a670d)
It makes no sense to use _18 listopad_ form, we are always using _18 listopada_, even google corrects this when you type _18 listopad_ in it

I was looking for api in **arrow** allowing to change months typing, but it seems that it's impossible without hardcoding it.

The correct array of polish months should looks this way:
[ 'Stycznia', 'Lutego', 'Marca', 'Kwietnia', 'Maja', 'Czerwca', 'Lipca', 'Sierpnia', 'Września', 'Października', 'Listopada', 'Grudnia' ]

**Comment by ownaginatious** [comment]
Hmm, I see. I think the real solution here would be to correct the month names to your list in `arrow` [here](https://github.com/crsmithdev/arrow/blob/master/arrow/locales.py#L689), since the current list doesn't work for anything. Looks like people are having grammar issues with other locales as well (e.g. [Arabic](https://github.com/crsmithdev/arrow/pull/430)).

I'm a bit fed up with `arrow`, since the maintainer is awful at addressing issues and PRs in a timely manner (last merge was literally 4 months ago).

I'll start looking into [`dateparser`](https://github.com/scrapinghub/dateparser). As you can see, the locale file, at least for Polish (see [here](https://github.com/scrapinghub/dateparser/blob/master/data/languagefiles/pl.yaml)), is far more complete and comprehensive.

**Comment by MeQuake** [comment]
Thank you! I've implemented `dateparser `and used it when `arrow` couldn't parse date, you can check it in this [commit](https://github.com/MeQuake/fbchat-archive-parser/commit/17eec5b6487b996a973a630cca60574fe9af8e04):

This was enough to pass all tests. I also successfully parsed my archive through your tool!

Unfortunately `dateparser `can't be used instead of `arrow `because some of already supported languages aren't supported by `dateparser`. These languages are: **Norwegian**, **Slovenian**, **Swedish**
Also, **Italian** language is supported by the dateparser, but **Italian** test didn't pass.

**Comment by ownaginatious** [comment]
Yeah, I tried implementing `dateparser` usage myself and realized that support was lacking for a lot of languages, and others weren't filled out for all cases (e.g. Czech). The maintainer of that library also isn't very good at dealing with PRs :/

Anyway, I believe I've implemented a solution that _should_ work for all supported languages and probably most of the languages people will care about going forward. I ended up using `babel` which you suggested earlier, since it seems to have the best language coverage. I'm using it in combination with `arrow` as a fallback, since apparently only `arrow` is correct for Facebook's Czech output :/

It's on `master` now. Could you try applying your changes [here](https://github.com/MeQuake/fbchat-archive-parser/commit/dfb33e931cbcd95d846b08a0c1cc67d3322a670d) against it and make a PR to add Polish language support if it works?

Thanks!

**Comment by ownaginatious** [comment]
I integrated the branch myself and it's now available on `master`. I'll push a new PyPI version when the next feature is added.
