### ISSUE TITLE
Streaming Parser crashes when redirecting to a file

### ISSUE THREAD

**Issue by cmanaog** [ownaginatious/fbchat-archive-parser#7]
Hi there again! Thanks for the speedy response.

This bug is a little vague. When I try running

fbcap ./messages.htm -f json > file.json

This always happens

The streaming parser crashed due to malformed XML. Falling back to the less strict/efficient python html.parser. It may take a while before you see output... 

However, if I do it without the '> file.json' the streaming works normally.

Thanks again!

**Comment by ownaginatious** [comment]
Hey there,

That's actually the intended behaviour. By default, this tool tries to use a faster parser that takes less memory. Unfortunately, that parser also requires well-formed XML, which isn't always what Facebook gives back. I don't have enough sample data to determine why.

So if that parser crashes, as a fallback it'll use a different slower and less efficient parser that is a lot less sensitive to poorly formed XML. It appears that that's what's happened with yours. The message that is printed out is actually just a warning for when that happens and comes out on `stderr`.

If you look in your `file.json`, all the JSON that was outputted over `stdout` should be there. You probably just didn't see it without the `> file.json` because it got pushed off screen  in your terminal super fast.

If you're still not seeing anything in `file.json`, please let me know and I'll investigate :)

**Comment by cmanaog** [comment]
It's in the `file.json`! It seems though that the faster parser crashes whenever I try to run with 
`>file.json` the faster parser crashes but when I run the command without `>file.json` the faster parser always works (I can see the progress too). Sorry if I'm describing this kind of weirdly. 

Also, this is a separate issue, but when I try this command 
`fbcap ./messages.htm -t 'FirstName Lastname, FirstName LastName, Firstname Lastname, Firstname Lastname' -f json > file.json` (where everyone has different first and last names) it doesn't return any threads. Any idea about what I might be doing wrong? 

Thanks again! You're really helpful  👍

**Comment by ownaginatious** [comment]
Yeah, it doesn't display when you redirect to a file. You brought up a good point though... I might change that later on so that the processing output goes to `stderr` instead.

Cool, glad you figured it out :)

**Comment by cmanaog** [comment]
Hey there!

I'm still having a little trouble with the second problem. When I run `-f stats` I can see the thread that I was talking about. But when I run `-t [list of names]` it says there's no conversation history. I can always extract it from `fbcap ./messages.htm -f json > file.json` but it would be a lot easier if I could just pull out the one thread I want. Any idea why I can't pull the specific thread down?

**Comment by ownaginatious** [comment]
Can you give me an example of the names you're seeing in the `-f stats` output and how you're putting them into the `-t` arguments?

**Comment by cmanaog** [comment]
> Top 10 longest threads:
> 
>   [1] Joe Banana, Casey Apple, Marwyn Mango, Victor Grape (362703)
>       - Joe Banana [95975|26.46%]
>       - [Me] [92390|25.47%]
>       - Victor Grape [83107|22.91%]
>       - Casey Apple [62133|17.13%]
>       - Marywyn Mango [14981|4.13%]
>       - Marwin Mango [13251|3.65%]
>       - Casey Grannysmith [866|0.24%]

like I said earlier some people had their name change (and obviously I changed people's name for privacy reasons).

The `-t` argument looks like this:

`fbcap ./messages.htm -t 'Joe Banana, Casey Apple, Marwyn Mango, Victor Grape' -f json > file.json`

While watching the processing output, I would see it saying `Skipping thread with [Joe Banana, Casey Apple, Marwyn Mango, Victor Grape]` or something like that.

**Comment by ownaginatious** [comment]
Ah, I think I found the issue! Try version `0.7post2`.

**Comment by cmanaog** [comment]
Hey there! It worked. Thanks so much!
