### ISSUE TITLE
Extract just the raw chat history (no names, dates, files etc) for text analysis  

### ISSUE THREAD

**Issue by wadbr** [ownaginatious/fbchat-archive-parser#83]
Can this be achieved with the current build?  

It would be very useful for text mining/analysis (specially as all the extra info adds about double the size of the files extracted and makes it more demanding for the algorithms to mine the text)

**Comment by ownaginatious** [comment]
Hi there!

Someone asked me about this before and I'm rather hesitant to add it in since it's a fairly niche feature. To be honest, unless you're doing text mining in super high volume or on a microcontroller, I can't see how reducing the size of the output will be a huge gain.

You can achieve what you're asking fairly easily with the CSV output in Python

```
fbcap messages messages.htm -f csv > my_message_output.csv
```

```python
import csv

with open('./my_message_output.csv', 'r') as f:
    for row in csv.reader(f):
        print(row[-1])
```

**Comment by wadbr** [comment]
Oh I didnt even think about csv! Thank you, this would be very helpful! 

About the file size, my normal text output is around 200mb, I'm using [SPMF](http://www.philippe-fournier-viger.com/spmf/index.php) for data minning, and it is a real pain to work with in regards to larger files like this, a 200mb file requires around 30gigs of memory (which I think is a bug but I'm not versed in Java to be able to dig into it) so that was why I was looking to reduce my file size.

**Comment by ownaginatious** [comment]
Closing as this project is being deprecated.
